import { RequestManager } from './RequestManager.js';
import { RESTClientOptions } from './RESTClient.js';
export declare const DefaultDiscordOptions: RESTClientOptions;
export * from './APIRequest.js';
export * from './BucketQueueManager.js';
export * from './RequestManager.js';
export * from './RESTClient.js';
export * from './RESTError.js';
export * from './REST.js';
export { RequestManager as default, RequestManager as Client };
